import type {
  EnergyConstraint,
  OptimizationSettings,
  PlantResource,
  PowerProfilePoint,
  ScheduleAssignment,
  TestBench,
  TestItem,
  TestRecipe,
  TestRecord,
  UtiliqState,
} from "./utiliq-types";

export const DEMO_NOW = "2026-06-02T10:30:00";
export const DEMO_DAY = "2026-06-02";

const chp408: PowerProfilePoint[] = [
  { offsetMinutes: 0, powerMW: 0.4 },
  { offsetMinutes: 30, powerMW: 1.8 },
  { offsetMinutes: 90, powerMW: 2.8 },
  { offsetMinutes: 210, powerMW: 2.4 },
  { offsetMinutes: 300, powerMW: 0.8 },
];

const chp412: PowerProfilePoint[] = [
  { offsetMinutes: 0, powerMW: 0.5 },
  { offsetMinutes: 45, powerMW: 2.6 },
  { offsetMinutes: 120, powerMW: 3.6 },
  { offsetMinutes: 300, powerMW: 3.0 },
  { offsetMinutes: 390, powerMW: 0.9 },
];

const generatorG450: PowerProfilePoint[] = [
  { offsetMinutes: 0, powerMW: -0.8 },
  { offsetMinutes: 60, powerMW: 1.5 },
  { offsetMinutes: 150, powerMW: 4.2 },
  { offsetMinutes: 300, powerMW: 3.7 },
  { offsetMinutes: 420, powerMW: 1.2 },
];

const powerPack: PowerProfilePoint[] = [
  { offsetMinutes: 0, powerMW: -1.6 },
  { offsetMinutes: 60, powerMW: -2.8 },
  { offsetMinutes: 180, powerMW: -3.5 },
  { offsetMinutes: 300, powerMW: -2.4 },
  { offsetMinutes: 360, powerMW: -0.9 },
];

const heatPumpCop: PowerProfilePoint[] = [
  { offsetMinutes: 0, powerMW: -0.4 },
  { offsetMinutes: 30, powerMW: -1.4 },
  { offsetMinutes: 90, powerMW: -2.6 },
  { offsetMinutes: 210, powerMW: -3.1 },
  { offsetMinutes: 300, powerMW: -1.2 },
];

export const demoRecipes: TestRecipe[] = [
  {
    id: "recipe-chp-408-full-load",
    name: "CHP full-load acceptance",
    description:
      "Ramp, synchronized full-load run, emissions hold, and shutdown validation for Agenitor 408 units.",
    defaultDurationHours: 5,
    requiredBenchType: "CHP dyno",
    setupTimeMinutes: 45,
    cooldownTimeMinutes: 30,
    expectedPowerProfile: chp408,
    requiredOperatorSkill: "CHP senior operator",
  },
  {
    id: "recipe-chp-412-heat-run",
    name: "CHP heat-run endurance",
    description:
      "Extended thermal performance and generator export profile validation for Agenitor 412 units.",
    defaultDurationHours: 6.5,
    requiredBenchType: "CHP dyno",
    setupTimeMinutes: 60,
    cooldownTimeMinutes: 45,
    expectedPowerProfile: chp412,
    requiredOperatorSkill: "CHP senior operator",
  },
  {
    id: "recipe-generator-g450-grid",
    name: "G450 grid compliance",
    description:
      "Load acceptance, frequency response, and export compliance checks for industrial generators.",
    defaultDurationHours: 7,
    requiredBenchType: "Generator bench",
    setupTimeMinutes: 60,
    cooldownTimeMinutes: 60,
    expectedPowerProfile: generatorG450,
    requiredOperatorSkill: "Grid compliance",
  },
  {
    id: "recipe-heat-pump-cop-validation",
    name: "Heat pump COP validation",
    description:
      "High-load thermal output and coefficient-of-performance validation for industrial heat pumps.",
    defaultDurationHours: 5,
    requiredBenchType: "Heat pump bench",
    setupTimeMinutes: 45,
    cooldownTimeMinutes: 45,
    expectedPowerProfile: heatPumpCop,
    requiredOperatorSkill: "Thermal systems",
  },
];

export const demoBenches: TestBench[] = [
  {
    id: "TB-01",
    name: "TB-01 CHP Dyno",
    benchType: "CHP dyno",
    status: "running",
    minPowerMW: 0,
    maxPowerMW: 4.5,
    location: "Hall B - Bay 1",
    compatibleRecipeIds: [
      "recipe-chp-408-full-load",
      "recipe-chp-412-heat-run",
      "recipe-generator-g450-grid",
    ],
    currentTestItemId: "ti-1042",
  },
  {
    id: "TB-02",
    name: "TB-02 Heat Pump Bench",
    benchType: "Heat pump bench",
    status: "available",
    minPowerMW: -3.5,
    maxPowerMW: 0,
    location: "Hall B - Bay 2",
    compatibleRecipeIds: ["recipe-heat-pump-cop-validation"],
  },
];

const item = (
  id: string,
  serialNumber: string,
  modelNumber: string,
  modelName: string,
  customerName: string,
  orderId: string,
  dateManufactured: string,
  readyForTestDate: string,
  deadline: string,
  priority: TestItem["priority"],
  status: TestItem["status"],
  testRecipeId: string,
  compatibleBenchIds: string[],
  notes?: string,
): TestItem => {
  const recipe = demoRecipes.find((candidate) => candidate.id === testRecipeId)!;
  return {
    id,
    serialNumber,
    modelNumber,
    modelName,
    customerName,
    orderId,
    dateManufactured,
    readyForTestDate,
    deadline,
    priority,
    status,
    testRecipeId,
    compatibleBenchIds,
    estimatedDurationHours: recipe.defaultDurationHours,
    setupTimeMinutes: recipe.setupTimeMinutes,
    cooldownTimeMinutes: recipe.cooldownTimeMinutes,
    expectedPowerProfile: recipe.expectedPowerProfile,
    notes,
  };
};

export const demoTestItems: TestItem[] = [
  item(
    "ti-1042",
    "UTQ-2026-1042",
    "AG408",
    "Agenitor 408 CHP Unit",
    "2G Energy",
    "2G-78210",
    "2026-05-28",
    "2026-06-01",
    "2026-06-05T17:00:00",
    "high",
    "waiting",
    "recipe-chp-408-full-load",
    ["TB-01"],
    "Customer delivery truck booked for Friday.",
  ),
  item(
    "ti-1043",
    "UTQ-2026-1043",
    "AG412",
    "Agenitor 412 CHP Unit",
    "2G Energy",
    "2G-78211",
    "2026-05-29",
    "2026-06-01",
    "2026-06-06T12:00:00",
    "normal",
    "waiting",
    "recipe-chp-412-heat-run",
    ["TB-01"],
  ),
  item(
    "ti-1045",
    "HP-900-2026-0871",
    "HP900",
    "Industrial Heat Pump HP-900",
    "Damen Thermal",
    "DAM-91207",
    "2026-05-27",
    "2026-06-01",
    "2026-06-05T12:00:00",
    "high",
    "waiting",
    "recipe-heat-pump-cop-validation",
    ["TB-02"],
  ),
  item(
    "ti-1044",
    "2G-AGG-2026-1182",
    "AG408",
    "Agenitor 408 CHP Unit",
    "2G Energy",
    "2G-78302",
    "2026-05-30",
    "2026-06-02",
    "2026-06-03T17:00:00",
    "urgent",
    "waiting",
    "recipe-chp-408-full-load",
    ["TB-01"],
    "Expedite due to delayed site commissioning.",
  ),
  item(
    "ti-1048",
    "HP-750-2026-0314",
    "HP750",
    "Industrial Heat Pump HP-750",
    "Damen Thermal",
    "DAM-33881",
    "2026-05-31",
    "2026-06-02",
    "2026-06-06T16:00:00",
    "normal",
    "waiting",
    "recipe-heat-pump-cop-validation",
    ["TB-02"],
  ),
  item(
    "ti-1038",
    "UTQ-2026-1038",
    "AG408",
    "Agenitor 408 CHP Unit",
    "2G Energy",
    "2G-78191",
    "2026-05-22",
    "2026-05-25",
    "2026-05-29T12:00:00",
    "normal",
    "waiting",
    "recipe-chp-408-full-load",
    ["TB-01"],
  ),
];

// Demo starts with an empty schedule so the optimizer can be run live in a demo.
export const demoAssignments: ScheduleAssignment[] = [];

export const demoRecords: TestRecord[] = [
  {
    id: "tr-1036",
    testItemId: "ti-1036",
    serialNumber: "GEN-G450-2026-5514",
    modelName: "Industrial Generator G450",
    benchId: "TB-02",
    scheduledStart: "2026-05-29T07:00:00",
    scheduledEnd: "2026-05-29T15:00:00",
    actualStart: "2026-05-29T07:10:00",
    actualEnd: "2026-05-29T15:25:00",
    outcome: "pass",
    energyGeneratedMWh: 17.4,
    energyExportedMWh: 11.9,
    energyCurtailedMWh: 0.8,
    estimatedCostImpactEUR: 920,
    notes: "Frequency response accepted after minor ramp delay.",
  },
  {
    id: "tr-1037",
    testItemId: "ti-1037",
    serialNumber: "HP-750-2026-0308",
    modelName: "Industrial Heat Pump HP-750",
    benchId: "TB-02",
    scheduledStart: "2026-05-30T09:00:00",
    scheduledEnd: "2026-05-30T15:30:00",
    actualStart: "2026-05-30T09:00:00",
    actualEnd: "2026-05-30T15:35:00",
    outcome: "pass",
    energyConsumedMWh: 11.6,
    energyCurtailedMWh: 0,
    estimatedCostImpactEUR: -860,
    notes: "COP validation completed during low-price import window.",
  },
  {
    id: "tr-1038",
    testItemId: "ti-1038",
    serialNumber: "UTQ-2026-1038",
    modelName: "Agenitor 408 CHP Unit",
    benchId: "TB-01",
    scheduledStart: "2026-05-31T07:00:00",
    scheduledEnd: "2026-05-31T12:45:00",
    actualStart: "2026-05-31T07:00:00",
    actualEnd: "2026-05-31T12:40:00",
    outcome: "pass",
    energyGeneratedMWh: 12.1,
    energyExportedMWh: 9.2,
    energyCurtailedMWh: 0.2,
    estimatedCostImpactEUR: 780,
    notes: "Optimized against morning export headroom.",
  },
];

export const demoEnergyConstraint: EnergyConstraint = {
  maxGridImportMW: 4.5,
  maxGridExportMW: 5,
  batteryCapacityMWh: 12,
  batteryStateOfChargePercent: 62,
  facilityBaseLoadMW: 1.4,
  electricityPriceProfile: [
    { time: "06:00", eurPerMWh: 112 },
    { time: "10:00", eurPerMWh: 138 },
    { time: "14:00", eurPerMWh: 168 },
    { time: "18:00", eurPerMWh: 194 },
  ],
  feedInTariffProfile: [
    { time: "06:00", eurPerMWh: 72 },
    { time: "10:00", eurPerMWh: 64 },
    { time: "14:00", eurPerMWh: 48 },
    { time: "18:00", eurPerMWh: 58 },
  ],
};

export const demoOptimizationSettings: OptimizationSettings = {
  preset: "balanced",
  weights: {
    meetDeadlines: 78,
    reduceEnergyCost: 58,
    avoidGridCaps: 86,
    maximizeUtilization: 64,
    reduceOvertime: 48,
    minimizeCurtailment: 74,
  },
};

export const demoResources: PlantResource[] = [
  {
    id: "TB-01",
    name: "TB-01 CHP Dyno",
    type: "Test Bench",
    status: "running",
    location: "Hall B - Bay 1",
    currentMW: 2.8,
    benchType: "CHP dyno",
    minPowerMW: 0,
    maxPowerMW: 4.5,
    compatibleRecipeIds: [
      "recipe-chp-408-full-load",
      "recipe-chp-412-heat-run",
      "recipe-generator-g450-grid",
    ],
    compatibleTestTypes: ["CHP dyno", "Generator bench"],
    utilizationPercent: 62,
  },
  {
    id: "TB-02",
    name: "TB-02 Heat Pump Bench",
    type: "Test Bench",
    status: "available",
    location: "Hall B - Bay 2",
    currentMW: 0,
    benchType: "Heat pump bench",
    minPowerMW: -3.5,
    maxPowerMW: 0,
    compatibleRecipeIds: ["recipe-heat-pump-cop-validation"],
    compatibleTestTypes: ["Heat pump bench"],
    utilizationPercent: 28,
  },
  {
    id: "GRID-01",
    name: "Main Grid Connection",
    type: "Grid",
    status: "connected",
    location: "Substation",
    currentMW: 0,
    maxGridImportMW: 4.5,
    maxGridExportMW: 5,
    utilizationPercent: 34,
  },
  {
    id: "BAT-01",
    name: "Battery Buffer",
    type: "Battery",
    status: "charging",
    location: "Hall A - Utility Room",
    currentMW: 0.2,
    batteryCapacityMWh: 12,
    maxChargeDischargeMW: 2,
    batteryStateOfChargePercent: 62,
    utilizationPercent: 62,
  },
  {
    id: "PV-01",
    name: "Rooftop PV",
    type: "PV",
    status: "generating",
    location: "Roof North",
    currentMW: 0.4,
    maxGenerationMW: 1.1,
    currentGenerationMW: 0.4,
    utilizationPercent: 38,
  },
  {
    id: "GEN-01",
    name: "Backup Generator",
    type: "Generator",
    status: "standby",
    location: "Hall A - Bay 1",
    currentMW: 0,
    maxGenerationMW: 2.5,
    currentGenerationMW: 0,
    utilizationPercent: 0,
  },
  {
    id: "TB-03",
    name: "TB-03 Generator Dyno",
    type: "Test Bench",
    status: "running",
    location: "Hall B - Bay 3",
    currentMW: 3.2,
    benchType: "Generator bench",
    minPowerMW: 0,
    maxPowerMW: 5,
    compatibleRecipeIds: ["recipe-generator-g450-grid"],
    compatibleTestTypes: ["Generator bench"],
    utilizationPercent: 71,
  },
  {
    id: "TB-04",
    name: "TB-04 E-Axle Bench",
    type: "Test Bench",
    status: "running",
    location: "Hall C - Bay 1",
    currentMW: -2.1,
    benchType: "E-drive bench",
    minPowerMW: -3,
    maxPowerMW: 0,
    compatibleTestTypes: ["E-drive bench"],
    utilizationPercent: 55,
  },
  {
    id: "TB-05",
    name: "TB-05 Battery Pack Bench",
    type: "Test Bench",
    status: "available",
    location: "Hall C - Bay 2",
    currentMW: 0,
    benchType: "Battery cycler",
    minPowerMW: -2.5,
    maxPowerMW: 2.5,
    compatibleTestTypes: ["Battery cycler"],
    utilizationPercent: 18,
  },
  {
    id: "LB-01",
    name: "Resistive Load Bank",
    type: "Load Bank",
    status: "running",
    location: "Hall A - Bay 2",
    currentMW: -1.8,
    maxConsumptionMW: 3,
    currentConsumptionMW: 1.8,
    utilizationPercent: 60,
  },
  {
    id: "COOL-01",
    name: "Chiller Plant",
    type: "Cooling",
    status: "running",
    location: "Hall A - Utility Room",
    currentMW: -0.9,
    maxConsumptionMW: 1.4,
    currentConsumptionMW: 0.9,
    utilizationPercent: 64,
  },
  {
    id: "AIR-01",
    name: "Compressor Station",
    type: "Compressed Air",
    status: "running",
    location: "Hall A - Utility Room",
    currentMW: -0.6,
    maxConsumptionMW: 0.9,
    currentConsumptionMW: 0.6,
    utilizationPercent: 67,
  },
  {
    id: "PV-02",
    name: "Carport PV Array",
    type: "PV",
    status: "generating",
    location: "Yard - South",
    currentMW: 0.5,
    maxGenerationMW: 0.8,
    currentGenerationMW: 0.5,
    utilizationPercent: 63,
  },
  {
    id: "FUEL-01",
    name: "Fuel Supply Skid",
    type: "Fuel Supply",
    status: "standby",
    location: "Yard - North",
    currentMW: 0,
    utilizationPercent: 0,
  },
];

export const createDemoState = (): UtiliqState => ({
  testItems: demoTestItems.map((testItem) => ({
    ...testItem,
    expectedPowerProfile: [...testItem.expectedPowerProfile],
  })),
  recipes: demoRecipes.map((recipe) => ({
    ...recipe,
    expectedPowerProfile: [...recipe.expectedPowerProfile],
  })),
  benches: demoBenches.map((bench) => ({
    ...bench,
    maintenanceWindows: bench.maintenanceWindows?.map((window) => ({ ...window })),
  })),
  assignments: demoAssignments.map((assignment) => ({
    ...assignment,
    warnings: assignment.warnings?.map((warning) => ({ ...warning })),
    optimizationReason: [...(assignment.optimizationReason ?? [])],
  })),
  records: demoRecords.map((record) => ({ ...record })),
  energyConstraint: {
    ...demoEnergyConstraint,
    electricityPriceProfile: demoEnergyConstraint.electricityPriceProfile?.map((point) => ({
      ...point,
    })),
    feedInTariffProfile: demoEnergyConstraint.feedInTariffProfile?.map((point) => ({ ...point })),
  },
  optimizationSettings: {
    ...demoOptimizationSettings,
    weights: { ...demoOptimizationSettings.weights },
  },
  resources: demoResources.map((resource) => ({
    ...resource,
    compatibleRecipeIds: resource.compatibleRecipeIds
      ? [...resource.compatibleRecipeIds]
      : undefined,
    compatibleTestTypes: resource.compatibleTestTypes
      ? [...resource.compatibleTestTypes]
      : undefined,
    maintenanceWindows: resource.maintenanceWindows?.map((window) => ({ ...window })),
  })),
});
