/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as LiveEnergyRouteImport } from './routes/live-energy'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FloorLayoutRouteImport } from './routes/floor-layout'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveEnergyRoute = LiveEnergyRouteImport.update({
  id: '/live-energy',
  path: '/live-energy',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FloorLayoutRoute = FloorLayoutRouteImport.update({
  id: '/floor-layout',
  path: '/floor-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/assets': typeof AssetsRoute
  '/floor-layout': typeof FloorLayoutRoute
  '/history': typeof HistoryRoute
  '/live-energy': typeof LiveEnergyRoute
  '/queue': typeof QueueRoute
  '/records': typeof RecordsRoute
  '/resources': typeof ResourcesRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/assets': typeof AssetsRoute
  '/floor-layout': typeof FloorLayoutRoute
  '/history': typeof HistoryRoute
  '/live-energy': typeof LiveEnergyRoute
  '/queue': typeof QueueRoute
  '/records': typeof RecordsRoute
  '/resources': typeof ResourcesRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/assets': typeof AssetsRoute
  '/floor-layout': typeof FloorLayoutRoute
  '/history': typeof HistoryRoute
  '/live-energy': typeof LiveEnergyRoute
  '/queue': typeof QueueRoute
  '/records': typeof RecordsRoute
  '/resources': typeof ResourcesRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/assets'
    | '/floor-layout'
    | '/history'
    | '/live-energy'
    | '/queue'
    | '/records'
    | '/resources'
    | '/schedule'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/assets'
    | '/floor-layout'
    | '/history'
    | '/live-energy'
    | '/queue'
    | '/records'
    | '/resources'
    | '/schedule'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/assets'
    | '/floor-layout'
    | '/history'
    | '/live-energy'
    | '/queue'
    | '/records'
    | '/resources'
    | '/schedule'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  AssetsRoute: typeof AssetsRoute
  FloorLayoutRoute: typeof FloorLayoutRoute
  HistoryRoute: typeof HistoryRoute
  LiveEnergyRoute: typeof LiveEnergyRoute
  QueueRoute: typeof QueueRoute
  RecordsRoute: typeof RecordsRoute
  ResourcesRoute: typeof ResourcesRoute
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-energy': {
      id: '/live-energy'
      path: '/live-energy'
      fullPath: '/live-energy'
      preLoaderRoute: typeof LiveEnergyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/floor-layout': {
      id: '/floor-layout'
      path: '/floor-layout'
      fullPath: '/floor-layout'
      preLoaderRoute: typeof FloorLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  AssetsRoute: AssetsRoute,
  FloorLayoutRoute: FloorLayoutRoute,
  HistoryRoute: HistoryRoute,
  LiveEnergyRoute: LiveEnergyRoute,
  QueueRoute: QueueRoute,
  RecordsRoute: RecordsRoute,
  ResourcesRoute: ResourcesRoute,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
